### ISSUE TITLE
Node version wrong

### ISSUE THREAD

**Issue by mikestreety** [t3easy/docker-surf#5]
Thanks for great docker image - has helped a lot!

Just ran into an issue where i have realised the `node` version is wrong in the `t3easy/surf:2-php7.3-composer2-node14` image 😁

![image](https://user-images.githubusercontent.com/354085/153579227-8c1bf121-06f7-42ff-af2a-0aacd9ef9b2c.png)

<img width="345" alt="image" src="https://user-images.githubusercontent.com/354085/153579300-d6bea498-8b4a-444e-a4ab-3e1c8bf63fb7.png">

**Comment by mikestreety** [comment]
WAIT. What am I talking about?! It's literally there in the screenshot 🤦

**Comment by t3easy** [comment]
Hi @mikestreety! Thanks for the feedback! Nice to read that things I publish are used by others besides me ;)

**Comment by mikestreety** [comment]
It's perfect, thanks! It means our backend developers can compile our front-end assets without needing node installed by running:

```
docker run --rm -v ${PWD}:/app -w /app --platform=linux/amd64 t3easy/surf:2-php7.3-composer2-node14 npm i
```

I also plan to look into surf in the future so will help with that - thanks!
